# To learn how to build a canny edge detector from scratch

In [1]:
import cv2 as c
import numpy as np
import matplotlib.pyplot as plt

### References:

https://towardsdatascience.com/canny-edge-detection-step-by-step-in-python-computer-vision-b49c3a2d8123

https://medium.com/@rohit-krishna/coding-canny-edge-detection-algorithm-from-scratch-in-python-232e1fdceac7

### Steps of Canny Edge Detection:

1) Gray scale conversion

2) Noise reduction

3) Gradient calculation

4) Non-maximum suppression

5) Double Thresholding and hysteresis

In [3]:
img = c.imread('images/robins.jpg',1)
grey = c.cvtColor(img, c.COLOR_BGR2GRAY)

c.imshow('robins: ', img)
c.imshow('grey',grey)

c.waitKey(0)
c.destroyAllWindows()

In [4]:
blur = c.GaussianBlur(grey, (5,5), 0)

c.imshow('blurred img',blur)
c.waitKey(0)
c.destroyAllWindows()

First trying sobel edge detection:

In [5]:
gX = c.Sobel(grey, ddepth=c.CV_32F, dx=1, dy=0, ksize=3)
gY = c.Sobel(grey, ddepth=c.CV_32F, dx=0, dy=1, ksize=3)

c.imshow('x ', gX)
c.imshow('y ', gY)
c.waitKey(0)
c.destroyAllWindows()

In [7]:
#using sobel operators

#mag = np.sqrt((gX**2) + (gY**2))
#mag = mag/mag.max() *255

gradx = gX - grey
grady = gY - grey

mag = np.sqrt(np.abs((gradx) + (grady)))

c.imshow('x2 ', gradx)
c.imshow('y2 ', grady)
c.imshow('mag', mag)
c.waitKey(0)
c.destroyAllWindows()

theta = np.arctan2(grady, gradx)
print("gradient angle",theta)

gradient angle [[-2.3561945 -2.4171875 -2.4196014 ... -2.6300714 -2.904655  -2.3561945]
 [-2.3820508 -2.4357364 -2.3186183 ... -2.5856967 -2.8224876 -2.1458685]
 [-2.4034035 -2.5523162 -2.2937758 ... -2.6351461 -2.8253365 -2.5247915]
 ...
 [-2.3561945 -2.3561945 -2.3561945 ... -1.8780551 -2.5023835 -2.3632865]
 [-2.3561945 -2.3561945 -2.3561945 ... -1.3719388 -2.300696  -2.4242709]
 [-2.3561945 -2.3561945 -2.3561945 ... -0.7140907 -2.223643  -2.3561945]]
