USING CSV MODULE/PACKAGE

In [16]:
import csv
with open("/home/AIML_Student/Documents/B34_aiml/Lab1/test1.csv","rt") as f: #csv.Dictreader -> print as dict
    data = csv.reader(f)
    for r in data:
        print(r)

['4', 'd', '4', 'k']
['5', 'e', '17', 'q']


In [17]:
with open("/home/AIML_Student/Documents/B34_aiml/Lab1/test1.csv","w") as f: #csv.Dictreader -> print as dict
    w = csv.writer(f,delimiter = ',',quotechar = '"',quoting = csv.QUOTE_MINIMAL) #overwrites files
    w.writerow(['4','d','4','k'])
    w.writerow(['5','e','17','q'])

In [14]:
with open("/home/AIML_Student/Documents/B34_aiml/Lab1/test1.csv","rt") as f: #csv.Dictreader -> print as dict
    data = csv.reader(f)
    for r in data:
        print(r)

['4', 'd', '4', 'k']
['5', 'e', '17', 'q']


USING PANDAS MODULE/PACKAGE

In [15]:
from pandas import DataFrame
c = [[1,'a','10','x'],[2,'b',20,'y'],[3,'c',11,'z']]
df = DataFrame(c,columns=['Sn','Name','Num','letter'])
export_csv = df.to_csv(r'/home/AIML_Student/Documents/B34_aiml/Lab1/test2_pandas.csv',index = True, header = True)
#can put index = None if not required 
print(df)

   Sn Name Num letter
0   1    a  10      x
1   2    b  20      y
2   3    c  11      z


installing a package: !pip install numpy (OR $pip)
checking: import numpy
in UBUNTU terminal: type spyder
then type:
import numpy 
import seaborn

LAB QUESTIONS

In [50]:
import numpy as np
#Q1
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
print("initial array: ",a)
b = a.reshape(3,3)
print("modified array: ",b)

initial array:  [0 1 2 3 4 5 6 7 8]
modified array:  [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [51]:
#Q2
n = a.size
for i in range(n): #using for loop
    if a[i]%2 !=0:
        a[i] = -1
print(a)
#using numpy
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
a[a%2!=0] = -1
print(a)

[ 0 -1  2 -1  4 -1  6 -1  8]
[ 0 -1  2 -1  4 -1  6 -1  8]


In [48]:
#Q3
x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89]) 
y = np.array([21, 7, 3, 45, 10, 29, 55, 4, 37, 18])
a = [] #storing in lists
b = []
c = np.array(99) #storing in array
d = np.array(99)

for i in range(x.size):
    if x[i] == y[i]:
        b.append(i)
        d = np.append(d,[i]) #axis 1 is row
    elif x[i] > y[i]:
        a.append(i)
        c =np.append(c,[i])
print("x>y: ",a,"\n",c)
print("x==y: ",b,"\n",d)

x>y:  [1, 2, 4, 5, 6, 7, 8, 9] 
 [99  1  2  4  5  6  7  8  9]
x==y:  [0] 
 [99  0]


In [38]:
#Q4
data = np.arange(100).reshape(5,-1)
print("data: \n",data)
data2 = data[:,[0,1,2,3]]
print("data2: \n",data2)

data: 
 [[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]]
data2: 
 [[ 0  1  2  3]
 [20 21 22 23]
 [40 41 42 43]
 [60 61 62 63]
 [80 81 82 83]]
