WEEK -09: K-Nearest Neighbour (K-NN)

In [4]:
import pandas as pd
import numpy as np
from math import sqrt

Q1)
We have data from the questionnaires survey (to ask people opinion) and objective testing with two attributes (acid durability and strength) to classify whether a special paper tissue is good or not. 
Here is four training samples as follows. 
Apply the K-nearest neighbour’s (KNN) algorithm when K=2, 3 and 4 to classify an instance (3, 7) as good or bad.

In [5]:
df = pd.read_csv('/home/AIML_Student/Documents/B34_aiml/Lab9/data.csv')

In [6]:
df

X1 = Acid Durability  X2 = Strength Y= Classification
0                     7              7               Bad
1                     7              4               Bad
2                     3              4              Good
3                     1              4              Good
4                     4              5               Bad
5                     3              5              Good
6                     4              6               Bad
7                     8              7               Bad
8                     7              9              Good
9                     8              8               Bad

In [7]:
cols = df.columns
cols

Index(['X1 = Acid Durability', 'X2 = Strength', 'Y= Classification'], dtype='object')

In [9]:
d = df.to_numpy()
d

array([[7, 7, 'Bad'],
       [7, 4, 'Bad'],
       [3, 4, 'Good'],
       [1, 4, 'Good'],
       [4, 5, 'Bad'],
       [3, 5, 'Good'],
       [4, 6, 'Bad'],
       [8, 7, 'Bad'],
       [7, 9, 'Good'],
       [8, 8, 'Bad']], dtype=object)

In [50]:
x1 = d[:, 0].reshape(-1, 1)
x2 = d[:, 1].reshape(-1, 1)
y = d[:, -1].reshape(-1, 1)

x = np.hstack((x1, x2))
print(x)

[[7 7]
 [7 4]
 [3 4]
 [1 4]
 [4 5]
 [3 5]
 [4 6]
 [8 7]
 [7 9]
 [8 8]]


In [51]:
test = [3, 7]

In [52]:
dist = []

n = d.shape[0] #number of rows /tuples

#calculating distances
for i in range(n):
    curr_dist = sqrt((test[0] - x1[i])**2 + (test[1] - x2[i])**2)
    curr = [curr_dist, y[i]]
    dist.append(curr)

dist_original = dist.copy()
print(dist)

[[4.0, array(['Bad'], dtype=object)], [5.0, array(['Bad'], dtype=object)], [3.0, array(['Good'], dtype=object)], [3.605551275463989, array(['Good'], dtype=object)], [2.23606797749979, array(['Bad'], dtype=object)], [2.0, array(['Good'], dtype=object)], [1.4142135623730951, array(['Bad'], dtype=object)], [5.0, array(['Bad'], dtype=object)], [4.47213595499958, array(['Good'], dtype=object)], [5.0990195135927845, array(['Bad'], dtype=object)]]


In [53]:
#sorting distances
dist.sort()

In [54]:
dist

[[1.4142135623730951, array(['Bad'], dtype=object)],
 [2.0, array(['Good'], dtype=object)],
 [2.23606797749979, array(['Bad'], dtype=object)],
 [3.0, array(['Good'], dtype=object)],
 [3.605551275463989, array(['Good'], dtype=object)],
 [4.0, array(['Bad'], dtype=object)],
 [4.47213595499958, array(['Good'], dtype=object)],
 [5.0, array(['Bad'], dtype=object)],
 [5.0, array(['Bad'], dtype=object)],
 [5.0990195135927845, array(['Bad'], dtype=object)]]

In [55]:
def find_class(l,k):
    g, b =0,0
    for i in range(k):
        if(l[i][1] == 'Good'):
            g+=1
        else:
            b+=1
    if(g > b):
        return 'Good'
    elif g==b:
        return 'Either'
    else:
        return 'Bad'

In [56]:
for i in [2, 3, 4]:
    pred = find_class(dist, i)
    print("for k = ",i," predicted class = ", pred)

for k =  2  predicted class =  Either
for k =  3  predicted class =  Bad
for k =  4  predicted class =  Either


Q2) 
Implement the Question number 1 with using scikit learn library. 
Plot the given samples Bad in Red color and Good in green color. Also plot the decision boundary. 
Calculate the distance using Euclidean, Manhattan, and Minkowski and compare.

In [57]:
from sklearn.neighbors import KNeighborsClassifier as knn

In [59]:
k = knn(n_neighbors = 3).fit(x, y.ravel())

In [67]:
t = np.array(test).reshape(1, 2)
y_pred = k.predict(t)
print("Using sklearn: ",y_pred)

Using sklearn:  ['Bad']


In [68]:
import matplotlib.pyplot as plt

In [75]:
print(x1[5])
print(x[5])

[3]
[3 5]


In [88]:
good = []
bad = []

for i in range(n):
    if(y[i]=='Bad'):
        bad.append(list(x[i]))
    else:
        good.append(list(x[i]))
print(bad)
bad = np.array(bad)
bad = bad.reshape(-1, 2)
print(bad)
print(bad[0])

[[7, 7], [7, 4], [4, 5], [4, 6], [8, 7], [8, 8]]
[[7 7]
 [7 4]
 [4 5]
 [4 6]
 [8 7]
 [8 8]]
[7 7]
